version: "3.9"
services:
  app_server:
    restart: on-failure
    image: node:alpine
    container_name: generic-stack
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c 'yarn install && yarn dev'
